Testing Heroku Postgres

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,12 +8,12 @@ jobs:
     docker:
       # Specify the version you desire here
       - image: circleci/php:7.3.9-apache-node-browsers
-      - image: circleci/mysql:5.7.28
-        environment:
-          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
-          MYSQL_DATABASE: $MYSQL_DATABASE
-          MYSQL_USER: $MYSQL_USER
-          MYSQL_PASSWORD: $MYSQL_PASSWORD
+      # - image: circleci/mysql:5.7.28
+      #   environment:
+      #     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
+      #     MYSQL_DATABASE: $MYSQL_DATABASE
+      #     MYSQL_USER: $MYSQL_USER
+      #     MYSQL_PASSWORD: $MYSQL_PASSWORD
           
 
       # Specify service dependencies here if necessary
@@ -29,28 +29,29 @@ jobs:
       - checkout
 
       - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
-      - run: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev 
+      - run: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libpq-dev
       - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
       - run: sudo docker-php-ext-install zip
       - run: sudo docker-php-ext-install exif
       - run: sudo docker-php-ext-install pdo_mysql
+      - run: sudo docker-php-ext-install pdo_pgsql
       - run: sudo docker-php-ext-install mbstring
       - run: sudo docker-php-ext-install gd
       - run:
       # Our primary container isn't MYSQL so run a sleep command until it's ready.
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
-      - run:
-          name: Install MySQL CLI
-          command: |
-            sudo apt-get install default-mysql-client
+      #     name: Waiting for MySQL to be ready
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z 127.0.0.1 3306 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 1
+      #       done
+      #       echo Failed waiting for MySQL && exit 1
+      # - run:
+      #     name: Install MySQL CLI
+      #     command: |
+      #       sudo apt-get install default-mysql-client
 
       # Download and cache dependencies
       - restore_cache:
